sudo: false
language: php
php:
    - 5.5
    - 5.6
    - 7
services: sqlite3
before_script:
    - composer self-update
    - composer install --prefer-source
script:
    - chmod -R 777 tests/logs
    - ./vendor/bin/phpunit
after_script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then php vendor/bin/coveralls -v; fi
